# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 291b773284f60fd04ab545531850297356639e3d1fba709c0bc21719c6572462d60df38ed51de335838fa889ee91516f797101e25fbba3e9500db140578b8771

test:
  secret_key_base: 6f6a064f06fea31be2baa94f31a783a255834792bdebed7d0c346392cfb6203e45f7c3bf0e9e39696136daea0e74f55e87273d2c46dead6f88e9b01fbf6eece6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
